[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
contracts = "Fo5yHR18hNooLoFzxYcjpi5BoUx5rhnxhzVRetpVeSsY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
